import {createClient} from '@supabase/supabase-js'
export const supabase =createClient("https://bsbybbsvduhquksrcrjt.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzYnliYnN2ZHVocXVrc3Jjcmp0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTIzNzAyMiwiZXhwIjoyMDk2ODEzMDIyfQ.Ypsl0lAyOE2I8ChcG-oGG02L45CYx4PCpHs2EWA-27Q")
